### ISSUE TITLE
Do we support Edge HTML?

### ISSUE THREAD

**Issue by TSaltedfishKing** [russelltg/web-mic#2]
I want to make my `Windows phone` useful more, but it only has `Edge HTML 15.15254`.
Visiting 192.168.xxx.xxx, 
"Allow this website use your microphone?"
"Only once"
Still display "Loading"
It's not affect while me shout at my phone.

**Comment by Alex-Programs** [comment]
Edge HTML is not IE, it's the engine used by MS before Edge switched to Chromium.

**Comment by russelltg** [comment]
I know pretty much nothing about that browser and have no way to test....if you get it to work feel free to send a PR!
